spring:
  data:
    mongodb:
      host: localhost
      username: mongo
      password: password
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090

